MedCheck/MedCheck/Controllers/HospitalController.cs
using MedCheck.DAL;
using MedCheck.Models;
using MedCheck.Models.ViewModels;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MedCheck.Controllers
{
    [Authorize(Roles = "admin")]
    public class HospitalController : Controller
    {
        private readonly MedCheckContext _context;

        public HospitalController(MedCheckContext context)
        {
            _context = context;
        }

        public IActionResult HospitalList()
        {
            return View(_context.Hospitals.ToList());
        }

        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(Hospital hospital)
        {
            _context.Add(hospital);
            _context.SaveChanges();
            return RedirectToAction("HospitalList");
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            _context.Hospitals.Remove(_context.Hospitals.Single(x => x.HospitalId == id));
            _context.SaveChanges();

            return RedirectToAction("HospitalList");
        }

        [HttpGet]
        public IActionResult Edit(int HospitalId)
        {
            var hospital = _context.Hospitals.Where(x => x.HospitalId == HospitalId).FirstOrDefault();

            //var data = new HospitalViewModel
            //{
            //    SecretCode = hospital.SecretCode,
            //    Street = hospital.Street,
            //    City = hospital.City,
            //    District = hospital.District,
            //    Name = hospital.Name
            //};


            return View(hospital);
        }

        [HttpPost]
        public IActionResult Edit(Hospital hospital)
        {
            //var dataCheck = new Hospital
            //{
            //    Name = hospital.Name,
            //    Street = hospital.Street,
            //    District = hospital.District,
            //    SecretCode = hospital.SecretCode,
            //    City = hospital.City,
            //};

            _context.Entry(hospital).State = EntityState.Modified;
            _context.SaveChanges();

            return RedirectToAction("HospitalList");
        }
    }
}

MedCheck/MedCheck/Controllers/RolesController.cs
using MedCheck.Models;
using MedCheck.Models.ViewModels;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MedCheck.Controllers
{
    [Authorize(Roles = "admin")]
    public class RolesController : Controller
    {
        RoleManager<IdentityRole> _roleManager;
        UserManager<MainUser> _userManager;
        public RolesController(RoleManager<IdentityRole> roleManager, UserManager<MainUser> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }
        public IActionResult Index()
        {
           return View(_roleManager.Roles.ToList());
        }

        public IActionResult Create() => View();
        [HttpPost]
        public async Task<IActionResult> Create(string name)
        {
            if (!string.IsNullOrEmpty(name))
            {
                IdentityResult result = await _roleManager.CreateAsync(new IdentityRole(name));
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View(name);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            IdentityRole role = await _roleManager.FindByIdAsync(id);
            if (role != null)
            {
                IdentityResult result = await _roleManager.DeleteAsync(role);
            }
            return RedirectToAction("Index");
        }

        public IActionResult UserList() => View(_userManager.Users.ToList());

        public async Task<IActionResult> Edit(string userId)
        {
            // get user
            MainUser user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                // get list of roles
                var userRoles = await _userManager.GetRolesAsync(user);
                var allRoles = _roleManager.Roles.ToList();
                ChangeRoleViewModel model = new ChangeRoleViewModel
                {
                    UserId = user.Id,
                    UserEmail = user.Email,
                    UserRoles = userRoles,
                    AllRoles = allRoles
                };
                return View(model);
            }

            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> Edit(string userId, List<string> roles)
        {
            // get user
            MainUser user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                // get user roles
                var userRoles = await _userManager.GetRolesAsync(user);
                // get all roles
                var allRoles = _roleManager.Roles.ToList();
                // get list of roles that were added
                var addedRoles = roles.Except(userRoles);
                // get list of roles that were deleted
                var removedRoles = userRoles.Except(roles);

                await _userManager.AddToRolesAsync(user, addedRoles);

                await _userManager.RemoveFromRolesAsync(user, removedRoles);

                return RedirectToAction("UserList");
            }

            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> DeleteUser(string id)
        {
            var user = await _userManager.FindByIdAsync(id);

            if (user == null)
            {
                ViewBag.ErrorMessage = $"User with Id = {id} cannot be found";
                return View("NotFound");
            }
            else
            {
                var result = await _userManager.DeleteAsync(user);

                if (result.Succeeded)
                {
                    return RedirectToAction("UserList");
                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }

                return View("UserList");
            }
        }
    }
}

MedCheck/MedCheck/Views/Roles/Create.cshtml
@model string

@{
    Layout = "_Layout";
}
@section status {
    @if (User.Identity.IsAuthenticated)
    {
        @*<p>@User.Identity.Name</p>

            <form method="post" asp-controller="Account" asp-action="Logout">
                <input type="submit" value="Log out" />
            </form>*@
        <div class="d-inline dropdown">
            <button class="btn btn-outline-dark btn-sm dropdown-toggle" type="button" data-toggle="dropdown">
                @User.Identity.Name
                <span class="caret"></span>
            </button>
            <div class="dropdown-menu dropdown-menu-right">
                <a class="dropdown-item small" asp-action="ProfileSettings" asp-controller="ProfileSettings">Profile Settings</a>
                <div class="dropdown-divider"></div>
                <form method="post" asp-controller="Account" asp-action="Logout">
                    <input class="dropdown-item small" asp-action="Logout" asp-controller="Account" type="submit" value="Log out" />
                </form>
            </div>
        </div>
    }
    else
    {
        <a class="btn btn-outline-dark btn-sm" asp-action="Login" asp-controller="Account">Log in</a>
        <a class="btn btn-outline-dark btn-sm" asp-action="Signup" asp-controller="Account">Sign up</a>
    }
}


<div asp-validation-summary="All" class="text-danger"></div>

<form asp-action="Create" method="post">
    <div class="form-group">
        <label for="name">New role</label>
        <input name="name" class="form-control" />
    </div>
    <button type="submit" class="btn btn-primary">Add</button>
</form>

MedCheck/MedCheck/Views/Roles/Edit.cshtml
@using Microsoft.AspNetCore.Identity
@model MedCheck.Models.ViewModels.ChangeRoleViewModel

@{
    Layout = "_Layout";
}
@section status {
    @if (User.Identity.IsAuthenticated)
    {
        @*<p>@User.Identity.Name</p>

            <form method="post" asp-controller="Account" asp-action="Logout">
                <input type="submit" value="Log out" />
            </form>*@
        <div class="d-inline dropdown">
            <button class="btn btn-outline-dark btn-sm dropdown-toggle" type="button" data-toggle="dropdown">
                @User.Identity.Name
                <span class="caret"></span>
            </button>
            <div class="dropdown-menu dropdown-menu-right">
                <a class="dropdown-item small" asp-action="ProfileSettings" asp-controller="ProfileSettings">Profile Settings</a>
                <div class="dropdown-divider"></div>
                <form method="post" asp-controller="Account" asp-action="Logout">
                    <input class="dropdown-item small" asp-action="Logout" asp-controller="Account" type="submit" value="Log out" />
                </form>
            </div>
        </div>
    }
    else
    {
        <a class="btn btn-outline-dark btn-sm" asp-action="Login" asp-controller="Account">Log in</a>
        <a class="btn btn-outline-dark btn-sm" asp-action="Signup" asp-controller="Account">Sign up</a>
    }
}

<h2>Change role for user @Model.UserEmail</h2>

<form asp-action="Edit" method="post">
    <input type="hidden" name="userId" value="@Model.UserId" />
    <div class="form-group">
        @foreach (IdentityRole role in Model.AllRoles)
        {
            <input type="checkbox" name="roles" value="@role.Name"
                   @(Model.UserRoles.Contains(role.Name) ? "checked=\"checked\"" : "") />@role.Name <br />
            }
    </div>
    <button type="submit" class="btn btn-primary">Save</button>
</form>

MedCheck/MedCheck/Views/Roles/Index.cshtml
@model IEnumerable<Microsoft.AspNetCore.Identity.IdentityRole>
@{
    Layout = "_Layout";
}
@section status {
    @if (User.Identity.IsAuthenticated)
    {
        @*<p>@User.Identity.Name</p>

            <form method="post" asp-controller="Account" asp-action="Logout">
                <input type="submit" value="Log out" />
            </form>*@
        <div class="d-inline dropdown">
            <button class="btn btn-outline-dark btn-sm dropdown-toggle" type="button" data-toggle="dropdown">
                @User.Identity.Name
                <span class="caret"></span>
            </button>
            <div class="dropdown-menu dropdown-menu-right">
                <a class="dropdown-item small" asp-action="ProfileSettings" asp-controller="ProfileSettings">Profile Settings</a>
                <div class="dropdown-divider"></div>
                <form method="post" asp-controller="Account" asp-action="Logout">
                    <input class="dropdown-item small" asp-action="Logout" asp-controller="Account" type="submit" value="Log out" />
                </form>
            </div>
        </div>
    }
    else
    {
        <a class="btn btn-outline-dark btn-sm" asp-action="Login" asp-controller="Account">Log in</a>
        <a class="btn btn-outline-dark btn-sm" asp-action="Signup" asp-controller="Account">Sign up</a>
    }
}

<h2>List of roles</h2>
<table class="table">
    @foreach (var role in Model)
    {
        <tr>
            <td>@role.Name</td>
            <td>
                <form asp-action="Delete" asp-route-id="@role.Id" method="post">
                    <button type="submit" class="btn btn-sm btn-danger">
                        Delete
                    </button>
                </form>
            </td>
        </tr>
    }
</table>
<a asp-action="Create">Add role</a>
<a asp-action="UserList">List of users</a>
<a asp-action="HospitalList" asp-controller="Hospital">List of hospitals</a>

MedCheck/MedCheck/Views/Roles/UserList.cshtml
@model IEnumerable<MedCheck.Models.MainUser>

@{
    Layout = "_Layout";
}
@section status {
    @if (User.Identity.IsAuthenticated)
    {
        @*<p>@User.Identity.Name</p>

            <form method="post" asp-controller="Account" asp-action="Logout">
                <input type="submit" value="Log out" />
            </form>*@
        <div class="d-inline dropdown">
            <button class="btn btn-outline-dark btn-sm dropdown-toggle" type="button" data-toggle="dropdown">
                @User.Identity.Name
                <span class="caret"></span>
            </button>
            <div class="dropdown-menu dropdown-menu-right">
                <a class="dropdown-item small" asp-action="ProfileSettings" asp-controller="ProfileSettings">Profile Settings</a>
                <div class="dropdown-divider"></div>
                <form method="post" asp-controller="Account" asp-action="Logout">
                    <input class="dropdown-item small" asp-action="Logout" asp-controller="Account" type="submit" value="Log out" />
                </form>
            </div>
        </div>
    }
    else
    {
        <a class="btn btn-outline-dark btn-sm" asp-action="Login" asp-controller="Account">Log in</a>
        <a class="btn btn-outline-dark btn-sm" asp-action="Signup" asp-controller="Account">Sign up</a>
    }
}

<h2>List of users</h2>
<table class="table">
    @foreach (var user in Model)
    {
        <tr>
            <td>@user.Email</td>
            <td>
                <form method="post" asp-action="DeleteUser" asp-route-id="@user.Id">
                    <a class="btn btn-sm btn-primary" asp-action="Edit" asp-route-userid="@user.Id">Access rights</a>
                    <button type="submit" class="btn btn-sm btn-danger">Delete</button>
                </form>
            </td>
        </tr>
    }
</table>